In [2]:
import numpy as np
import pandas as pd
import BHVReader

ModuleNotFoundError: No module named 'BHVReader'

In [3]:
data = pd.read_csv('May/20190527.trd', sep="|", header=None)

In [4]:
data

,0,1,2,3,4,5,6,7,8,9
0,50555747,BANKNIFTY,OPTIDX,20190530,PE,0,30000.0,10:08:30,17.350000,20.0
1,52011548,BANKNIFTY,OPTIDX,20190530,PE,0,31000.0,14:29:40,89.450000,20.0
2,87693079,HCLTECH,FUTSTK,20190530,FF,0,0.0,12:54:30,1062.650000,1400.0
3,94077443,RELIANCE,OPTSTK,20190530,CE,0,1300.0,14:44:47,25.800000,1000.0
4,1321014,NIFTY,OPTIDX,20190530,CE,0,12300.0,14:30:51,3.400000,150.0
...,...,...,...,...,...,...,...,...,...,...
6319110,94063332,PFC,FUTSTK,20190530,FF,0,0.0,14:33:09,119.900000,6200.0
6319111,94120969,PFC,FUTSTK,20190530,FF,0,0.0,15:16:57,119.349999,6200.0
6319112,93776960,NATIONALUM,FUTSTK,20190530,FF,0,0.0,09:24:28,50.350000,8000.0
6319113,94023006,MARUTI,OPTSTK,20190530,CE,0,7000.0,13:43:21,164.650000,75.0
6319114,87639545,GRASIM,OPTSTK,20190530,PE,0,820.0,11:36:27,0.600000,750.0

In [11]:
df = pd.read_csv('20190521.bhv', sep="|", header=None)

In [12]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,20190521,TATAPOWER,OPTSTK,20190530,CE,0,75.0,0.35,0.35,0.20000,0.20000,0.20000,1179000.0,360000.0,87300.0,31
1,20190521,ESCORTS,OPTSTK,20190530,PE,0,540.0,7.65,8.50,4.90000,6.65000,6.60000,105600.0,105600.0,705100.0,89
2,20190521,JUSTDIAL,OPTSTK,20190530,PE,0,560.0,2.80,4.00,1.50000,3.35000,1.50000,238000.0,119000.0,326270.0,82
3,20190521,ZEEL,OPTSTK,20190530,CE,0,470.0,1.45,1.75,1.40000,1.40000,1.40000,75400.0,7800.0,11765.0,6
4,20190521,HCLTECH,FUTSTK,20190627,FF,0,0.0,1076.70,1078.50,1061.79999,1063.09999,1064.04999,301700.0,74900.0,80233685.0,103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6843,20190521,TORNTPHARM,OPTSTK,20190627,CE,0,1700.0,26.75,26.75,26.75000,26.75000,26.75000,500.0,500.0,13375.0,1
6844,20190521,TATACHEM,OPTSTK,20190530,PE,0,620.0,19.40,23.80,18.70000,18.70000,18.70000,7500.0,12000.0,259462.5,16
6845,20190521,TATACHEM,OPTSTK,20190530,CE,0,610.0,19.25,21.90,12.00000,21.05000,20.00000,57750.0,58500.0,994012.5,75
6846,20190521,SAIL,OPTSTK,20190530,CE,0,48.0,4.00,4.25,3.60000,3.60000,3.60000,612000.0,48000.0,190200.0,4
6847,20190521,KOTAKBANK,OPTSTK,20190627,PE,0,1500.0,51.00,55.00,47.85000,53.65000,53.65000,4400.0,4400.0,228040.0,10